= Draft CityGML 2.0 Executable Test Suite

== Scope

This repository holds the source code of the Executable Test Suite (ETS) of the https://portal.ogc.org/files/?artifact_id=47842[CityGML 2.0] Standard.


== How to run the test suite using Docker

Run the following maven command from the root folder of the repository:

`mvn clean install -Dsource=8  docker:run -Pdocker`

From here, you can now access http://localhost:8081/teamengine to access the deployed teamengine with the CityGML 2.0 Test Suite.

You can log in as `ogctest`, with a password of ogctest.

== How to build the test suite

The test suite is built using https://maven.apache.org/[Apache Maven v3].

== How to run the test suite
The options for running the suite are summarized in

include::src/site/asciidoc/how-to-run-the-tests.adoc[]

== How to contribute

If you would like to get involved, you can:

* https://github.com/opengeospatial/ets-citygml20/issues[Report an issue] such as a defect or
an enhancement request
* Help to resolve an https://github.com/opengeospatial/ets-citygml20/issues?q=is%3Aopen[open issue]
* Fix a bug: Fork the repository, apply the fix, and create a pull request
* Add new tests: Fork the repository, implement and verify the tests on a new topic branch,
and create a pull request (don't forget to periodically rebase long-lived branches so
there are no extraneous conflicts)
